/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv` (hash: b0db46987bdf36b7b3134869d0978d1c)
interface __BaseEnv_CloudflareEnv {
	PLATFORM_AI_RATE_LIMITER: RateLimit;
	ASSETS: Fetcher;
	GITHUB_API_BASE_URL: "https://api.github.com";
	DEFAULT_LLM_PROVIDER: "deepseek";
	DEFAULT_LLM_MODEL: "deepseek-v4-flash";
	DEFAULT_LLM_BASE_URL: "https://api.deepseek.com";
	LLM_TIMEOUT_MS: "60000";
	PLATFORM_GITHUB_TOKEN: string;
	PLATFORM_LLM_API_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GITHUB_API_BASE_URL" | "DEFAULT_LLM_PROVIDER" | "DEFAULT_LLM_MODEL" | "DEFAULT_LLM_BASE_URL" | "LLM_TIMEOUT_MS" | "PLATFORM_GITHUB_TOKEN" | "PLATFORM_LLM_API_KEY">> {}
}
